export const QUESTIONS_POOL = [
    "💰 Who's gonna be rolling in cash first?",
    "🧟 Who'd outlast everyone in a zombie attack?",
    "🏆 Who'd totally win a reality show?",
    "🎤 Who'd kill it as a stand-up comic?",
    "📱 Who's gonna blow up on TikTok next?",
    "🕵️ Who'd solve crimes like Sherlock?",
    "🎂 Who'd forget their OWN birthday? lol",
    "🎭 Who does the best celeb impressions?",
    "🕶️ Who'd be the coolest secret agent?",
    "💬 Who'd text their crush 'hey dad' by accident?",
    "✈️ Who's definitely moving abroad someday?",
    "🧠 Who gives shockingly good advice?",
    "🎨 Whose art belongs in a museum?",
    "🎲 Who's the most unpredictable human?",
    "👗 Whose fits are always fire?",
    "📚 Who's writing a bestseller?",
    "🌍 Who's got wild travel stories?",
    "🗣️ Who could learn Spanish in a week?",
    "🤪 Who has the weirdest hobbies?",
    "💪 Whose pep talks would motivate you?",
    "🍔 Who'd win a hot dog contest?",
    "🍝 Who's secretly a food snob?",
    "🍟 Who could live off fries forever?",
    "👨‍🍳 Who makes insane home-cooked meals?",
    "🌶️ Who'd eat ghost peppers for fun?",
    "🍰 Who orders dessert first? Icon.",
    "🍽️ Who'd destroy an all-you-can-eat?",
    "🍕 Who'd invent pizza 2.0?",
    "☕ Who runs on caffeine alone?",
    "🍿 Who sneaks candy into movies?",
    "💼 Who's destined to be a startup boss?",
    "👨‍🏫 Who's giving TED Talks someday?",
    "🤝 Who could sell ice to a penguin?",
    "🧠 Who aces tests without trying?",
    "😴 Who'd sleep through their own meeting?",
    "✨ Who's landing their dream job?",
    "⏰ Who forgets deadlines constantly?",
    "🔬 Who's gonna cure diseases?",
    "📈 Who's getting promoted ASAP?",
    "🌏 Who's quitting to backpack forever?",
    "🎬 Who'd direct an Oscar winner?",
    "📺 Who binge-watches whole seasons?",
    "🧠 Who knows random facts?",
    "🌟 Who'd bump into Beyoncé?",
    "😭 Who cries at commercials?",
    "🎤 Who owns karaoke night?",
    "🎧 Who's the ultimate hype DJ?",
    "👘 Who'd go all-out at Comic-Con?",
    "🎵 Who's got playlist game?",
    "💃 Who wins the dance floor?"
];